<?php

namespace App\Services\BidSources\BidPrime;

use App\Services\BidSources\BidSourceResultDTO;
use Carbon\Carbon;

class FakeBidPrimeClient
{
    public function searchOpportunities(array $params = []): array
    {
        $opportunities = [];

        $sectors = ['Federal', 'State', 'Municipal', 'Utility', 'Education'];
        $agencies = [
            ['California Department of Technology', null],
            ['Texas Department of Information Resources', null],
            ['New York State Office of Technology', null],
            ['City of Chicago - Department of Innovation', null],
            ['Los Angeles Unified School District', null],
            ['Pacific Gas and Electric', null],
        ];

        for ($i = 1; $i <= 20; $i++) {
            [$agency, $subAgency] = $agencies[array_rand($agencies)];
            $postedDate = Carbon::now()->subDays(rand(1, 30));
            $dueDate = Carbon::now()->addDays(rand(7, 60));
            $sector = $sectors[array_rand($sectors)];

            $opportunities[] = new BidSourceResultDTO(
                externalId: 'BP-FAKE-' . str_pad($i, 5, '0', STR_PAD_LEFT),
                source: 'bidprime',
                title: "BidPrime {$sector} IT Services Opportunity {$i}",
                solicitationNumber: 'BP-' . strtoupper(uniqid()),
                agencyName: $agency,
                subAgencyName: $subAgency,
                naicsCode: ['541511', '541512', '541519'][array_rand(['541511', '541512', '541519'])],
                pscCode: null,
                setAsideType: null,
                contractType: 'RFP',
                estimatedValue: rand(25, 2000) * 1000.0,
                description: "BidPrime sourced {$sector} opportunity {$i}. This is a demonstration record generated by the fake BidPrime client for local development and testing.",
                postedDate: $postedDate,
                dueDate: $dueDate,
                placeOfPerformanceCity: null,
                placeOfPerformanceState: null,
                placeOfPerformanceCountry: 'US',
                sourceUrl: "https://bidprime.com/bid/fake-{$i}",
                rawData: ['bp_id' => "BP-FAKE-{$i}", 'sector' => $sector],
            );
        }

        return $opportunities;
    }

    public function getOpportunity(string $id): ?BidSourceResultDTO
    {
        $results = $this->searchOpportunities();
        foreach ($results as $r) {
            if ($r->externalId === $id) return $r;
        }
        return null;
    }
}
