<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

/**
 * A product datasheet generated by the Datasheet Writer: the user dumps spec
 * sheets / technical notes / product photos and the AI assembles a fully written,
 * branded datasheet. `sections` holds the generated content; `media` lists the
 * uploaded source files (spec docs + images) stored on the private local disk.
 */
class Datasheet extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'ulid', 'organization_id', 'created_by', 'product_name', 'model_number',
        'tagline', 'status', 'input_notes', 'source_text', 'sections', 'media', 'generated_at',
    ];

    protected $casts = [
        'sections' => 'array',
        'media' => 'array',
        'generated_at' => 'datetime',
    ];

    protected static function booted(): void
    {
        static::creating(fn (Datasheet $m) => $m->ulid ??= (string) Str::ulid());
    }

    public function scopeForOrganization(Builder $query, int $organizationId): Builder
    {
        return $query->where('organization_id', $organizationId);
    }

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /** Files of a given kind ('spec' or 'image') from the media list. */
    public function mediaOfKind(string $kind): array
    {
        return array_values(array_filter($this->media ?? [], fn ($m) => ($m['kind'] ?? null) === $kind));
    }
}
